nohup: ignoring input
 * Running on http://0.0.0.0:828/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 812-177-094
113.246.106.234 - - [27/Sep/2017 17:52:56] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 17:52:56] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 17:52:56] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 17:52:56] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:00:38] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:00:38] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:00:47] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:00:49] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:00:49] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:32] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:32] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:36] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:36] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:36] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:36] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:36] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:37] "GET /static/css/index.css HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
113.246.106.234 - - [27/Sep/2017 18:02:37] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:37] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:37] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:37] "GET /static/css/index.css HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
113.246.106.234 - - [27/Sep/2017 18:02:37] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:02:37] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:04:01] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:04:01] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:04:14] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:04:14] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:04:17] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:04:17] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:04:17] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:04:17] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:22] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:22] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:24] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:24] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:24] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:24] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:24] "GET / HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
113.246.106.234 - - [27/Sep/2017 18:05:24] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:24] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:05:24] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:02] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:02] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:02] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:02] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:02] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:02] "GET /static/css/index.css HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
113.246.106.234 - - [27/Sep/2017 18:06:02] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:02] "GET / HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:03] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:03] "GET /static/css/index.css HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
113.246.106.234 - - [27/Sep/2017 18:06:03] "GET /favicon.ico HTTP/1.1" 200 -
113.246.106.234 - - [27/Sep/2017 18:06:03] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.153.237 - - [27/Sep/2017 18:07:53] "GET /login HTTP/1.1" 200 -
113.246.153.237 - - [27/Sep/2017 18:07:53] "GET /static/css/index.css HTTP/1.1" 200 -
119.39.248.107 - - [27/Sep/2017 18:21:16] "GET /login HTTP/1.1" 200 -
119.39.248.107 - - [27/Sep/2017 18:21:16] "GET /static/css/index.css HTTP/1.1" 304 -
119.39.248.107 - - [27/Sep/2017 18:33:50] "POST /login HTTP/1.1" 302 -
119.39.248.107 - - [27/Sep/2017 18:33:50] "GET /host HTTP/1.1" 200 -
119.39.248.107 - - [27/Sep/2017 18:34:18] "POST /login HTTP/1.1" 302 -
119.39.248.107 - - [27/Sep/2017 18:34:18] "GET /host HTTP/1.1" 200 -
119.39.248.107 - - [27/Sep/2017 18:38:42] "POST /login HTTP/1.1" 302 -
119.39.248.107 - - [27/Sep/2017 18:38:42] "GET /host HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:48] "GET / HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:49] "GET / HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:49] "GET /static/css/index.css HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:49] "GET /static/css/background.jpg HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:50] "GET /favicon.ico HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:53] "GET / HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:53] "GET /static/css/index.css HTTP/1.1" 304 -
220.168.65.115 - - [27/Sep/2017 18:47:53] "GET /static/css/background.jpg HTTP/1.1" 304 -
220.168.65.115 - - [27/Sep/2017 18:47:54] "GET / HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:54] "GET /static/css/index.css HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:54] "GET /static/css/background.jpg HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 104] Connection reset by peer
220.168.65.115 - - [27/Sep/2017 18:47:54] "GET / HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:54] "GET /static/css/index.css HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:47:54] "GET /static/css/background.jpg HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:06] "GET /l HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:06] "GET /log HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:07] "GET /login HTTP/1.1" 200 -
183.136.238.206 - - [27/Sep/2017 18:48:08] "GET /l HTTP/1.1" 200 -
183.136.238.219 - - [27/Sep/2017 18:48:09] "GET /log HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:09] "GET /login HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:09] "GET /favicon.ico HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /login HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /static/css/index.css HTTP/1.1" 304 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /static/css/background.jpg HTTP/1.1" 304 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /login HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /static/css/index.css HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /static/css/background.jpg HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 104] Connection reset by peer
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /login HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /static/css/index.css HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /static/css/background.jpg HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 104] Connection reset by peer
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /login HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /static/css/index.css HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /static/css/background.jpg HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 104] Connection reset by peer
220.168.65.115 - - [27/Sep/2017 18:48:18] "GET /login HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:19] "GET /static/css/index.css HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:19] "GET /static/css/background.jpg HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:32] "POST /login HTTP/1.1" 302 -
220.168.65.115 - - [27/Sep/2017 18:48:32] "GET /host HTTP/1.1" 200 -
220.168.65.115 - - [27/Sep/2017 18:48:32] "GET /host HTTP/1.1" 200 -
113.246.111.96 - - [27/Sep/2017 19:15:24] "GET /login HTTP/1.1" 200 -
113.246.111.96 - - [27/Sep/2017 19:15:25] "GET /static/css/index.css HTTP/1.1" 304 -
113.246.111.96 - - [27/Sep/2017 19:15:27] "GET /login HTTP/1.1" 200 -
113.246.111.96 - - [27/Sep/2017 19:15:27] "GET /static/css/index.css HTTP/1.1" 304 -
113.246.111.96 - - [27/Sep/2017 19:15:41] "POST /login HTTP/1.1" 302 -
113.246.111.96 - - [27/Sep/2017 19:15:41] "GET /host HTTP/1.1" 200 -
113.246.187.146 - - [27/Sep/2017 20:20:47] "GET /login HTTP/1.1" 200 -
113.246.187.146 - - [27/Sep/2017 20:20:47] "GET /static/css/index.css HTTP/1.1" 304 -
113.246.111.71 - - [27/Sep/2017 21:32:35] "GET /login HTTP/1.1" 200 -
101.226.99.197 - - [27/Sep/2017 21:32:45] "GET /login HTTP/1.1" 200 -
113.246.111.71 - - [28/Sep/2017 00:30:55] "GET /login HTTP/1.1" 200 -
113.246.111.71 - - [28/Sep/2017 08:08:57] "GET /login HTTP/1.1" 200 -
113.246.111.71 - - [28/Sep/2017 08:08:57] "GET /static/css/index.css HTTP/1.1" 304 -
113.246.111.71 - - [28/Sep/2017 08:08:57] "GET /static/css/background.jpg HTTP/1.1" 304 -
113.246.111.71 - - [28/Sep/2017 08:09:41] "POST /login HTTP/1.1" 302 -
113.246.111.71 - - [28/Sep/2017 08:09:41] "GET /host HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:01:50] "GET /index.html HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:01:50] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:01:50] "GET /static/css/background.jpg HTTP/1.1" 304 -
113.246.153.211 - - [28/Sep/2017 09:14:03] "GET / HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:14:03] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:14:03] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:14:03] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:15:51] "GET / HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:15:51] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:15:56] "GET / HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:15:56] "GET /static/css/index.css HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:15:56] "GET /static/css/background.jpg HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 09:15:56] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:04] "GET /forget_passwd HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:04] "GET /js/bodymovin.js HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:04] "GET /js/data.js HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:05] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:10] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:34] "GET /register HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:34] "GET /static/js/bodymovin.js HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:34] "GET /static/js/data.js HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:04:37] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:08:35] "GET /host HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:08:35] "GET /favicon.ico HTTP/1.1" 200 -
 * Detected change in '/flask/gx/app/views.py', reloading
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
GET
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 812-177-094
113.246.153.211 - - [28/Sep/2017 10:13:52] "GET /host HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:13:52] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:13:52] "GET /host HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:13:53] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:13:59] "GET /magic HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:13:59] "GET /favicon.ico HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:14:06] "GET /magic/test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/flask/gx/app/views.py", line 154, in magic
    return render_template('<name>.html')
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib64/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib64/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: <name>.html
113.246.153.211 - - [28/Sep/2017 10:14:06] "GET /magic/test?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:14:06] "GET /magic/test?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:14:06] "GET /magic/test?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:14:06] "GET /magic/test?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:14:06] "GET /magic/test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
113.246.153.211 - - [28/Sep/2017 10:14:07] "GET /magic/test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/flask/gx/app/views.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/flask/gx/server.py", line 7, in <module>
    from app import app
  File "/flask/gx/app/__init__.py", line 6, in <module>
    from app import views
  File "/flask/gx/app/views.py", line 154
    return render_template(<name>+'.html') 
                           ^
SyntaxError: invalid syntax
